ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDraR0ixEOlpP3Ygr3AkcjUsAJf+xHi2Yia3E4/alPkls8SjNBGmCS3Fnr1z4bGFVP+5TQSNzqhIgtD5+VXmMh34WRPRmzzck7H/JQ5s6FGlzQeLrz2kZB2GCnsL4z79keem7DOgvdGojai9NkbJkoQqshwdEif85gvUl7fLXqiWE90KdIJbT3+BLvuZDAs+qr7tbD5A8/u7JK/GwGHu01CtNFZ5UHnAfZ5z4dQg7Cw0GgwegbA37pO/DvdpQ8JVvD1GsdKOZyIdtMiEPR1sS+sRXTqliw4YnI+ZzyaXx6s4pGbxEEoph8n06iF6EGD1w6l+8jfnU09VDKz8KIM/ICQ8lYRxJ5lRCrX/QrStSI6aActAxxm54ftYu6Wa/XKKiAPXLPjV5xNAlW7eta7kfjqKciooI8tWBC6RAF7Bx3rIkj8QANG8FmJWzKgAxhibx/jc7OPNpfoWC5C6CCSIktC6g0Ku7qUkzAZfcn5usr2JAvQPp3+aYFacjEYISVCyYLOANQffYAE66QiAyb7N117UWS2QUW9U7V9znLohAw+VbSVwUYkTrJ7sLnl+lEP/DL9mndxrz5awU0zazMa6xk17HFGYWTCCCPhRyMrrz+AfkHzMu/LAgfr64PhSUXuPfq1yXN5C6b3+lwtWbH4uOQ4UEcCJlNYrUvD1MNmaruIDw dev@yeah.si
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+2q1QBGE2fBrSHIqGjmdh+qdYV4VtQZOFi7MqW83BVj/vS16kfiGJGw0ke+yh0sGZK5aeaXsb7kuayngXXO7NpTgvzy9Li2T0vvzTNdsgr5Jysg66u7JQwYvYhtYHpZraa4PgQBEg7Fc7qwW/ULfTmIYdq6hWobuaPpE4DH3cG/mon9aS4uy+ULJkStvnTkfF2onlGup9mDIFlRnmfg1N4Ufl+WpThg7llvyPvyO4vUnjiqsJu66Vom6Yxn3IZU9dRF7qeJ4V/eUnhc7BsDaZZOWYbjUX+OguA2JqpgQ3+77KBFBpFJzg5prC5TsZAqCTlSdxIGTAXb1eZOoiAM4H sebastian.fuss@senacor.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgTFUPwvVwqJ72A7rYSzZDWdIvUHOnG9wTlIPcq9oBDmiUBAvOFMZgnZ9u+nf7UnF9X8rhQyN8wYetQ7ObNSQmStJ8/1pmNSRqf6WfDB1CFPWcu1PhU8H0YGXbRdJBDELs/cLy+tQ5dpL2O4d9jyxrRtwh8drPO70l8OrmaM6+0wRFhc1nz0hcNMNs9LDQslRBNIOMX9oqvmnaDHVOBnMc57lthC7NxVcD3qsEynk5tRhJ5LKzpjU7fZ4KOHwWp8efWx+DsgAvkG+wJ0w6lKeuMbjcmb8gSZID66LsY9H2JJK2hLtXvtTxWjby7uoEgdYuudzrXRDZ5nEbRtxKGRHZ michi@ranger
hostname: Rancher1

rancher:
  docker:
    tls: true
  network:
    dns:
      nameservers:
      - 10.90.0.15
      - 10.89.0.15
      - 8.8.8.8
      - 8.8.4.4
  interfaces:
      eth0:
        address: 10.90.0.87/23
        gateway: 10.90.0.1
        mtu: 1500
        dhcp: false
      eth1:
        dhcp: false
